name: Host automatico firebase
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          APIKEY: ${{ secrets.APIKEY }}
          AUTHDOMAIN: ${{ secrets.AUTHDOMAIN }}
          DATABASEURL: ${{ secrets.DATABASEURL }}
          PROJECTID: ${{ secrets.PROJECTID }}
          STORAGEBUCKET: ${{ secrets.STORAGEBUCKET }}
          MESSAGINGSENDERID: ${{ secrets.MESSAGINGSENDERID }}
          APPID: ${{ secrets.APPID }}
          MEASUREMENTID: ${{ secrets.MEASUREMENTID }}
