name: Host automatico firebase
on:
  push:
    branches:
      - master

jobs:
  
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - run: npm install
      - run: npm i @angular/cli 
      - run: npm run build -- --prod
      - name: Deploy to Firebase
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting --project redegresadospoli
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
          FIREBASE_PROJECT: redegresadospoli
          APIKEY: ${{ secrets.APIKEY }}
          AUTHDOMAIN: ${{ secrets.AUTHDOMAIN }}
          DATABASEURL: ${{ secrets.DATABASEURL }}
          PROJECTID: ${{ secrets.PROJECTID }}
          STORAGEBUCKET: ${{ secrets.STORAGEBUCKET }}
          MESSAGINGSENDERID: ${{ secrets.MESSAGINGSENDERID }}
          APPID: ${{ secrets.APPID }}
          MEASUREMENTID: ${{ secrets.MEASUREMENTID }}
